sudo: required
language: node_js
node_js:
- '10'
services:
- docker
env:
  global:
  - PROJECT_ID="fiery-booth-223812"
  - ZONE="asia-south1-a"
  - VERSION=$(jq -r '.version' package.json)
  - SHORT_SHA=$(echo $TRAVIS_COMMIT | cut -c1-7)
  - TAG=${VERSION}_${SHORT_SHA}_${TRAVIS_BUILD_NUMBER}
  - IMAGE_NAME=mckdemo/hit_men:$TAG
  - FULL_IMAGE_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_de67a91fce86_key -iv $encrypted_de67a91fce86_iv
  -in fiery-booth-223812-a833e36fb0c2.json.enc -out fiery-booth-223812-a833e36fb0c2.json
  -d
script:
- docker login -u _json_key -p "$(cat fiery-booth-223812-a833e36fb0c2.json)" https://gcr.io/fiery-booth-223812
- docker build -t $FULL_IMAGE_NAME .
- docker push $FULL_IMAGE_NAME
